$('#sysException').datagrid({
    title: '系统异常',
    iconCls: 'icon-search',
    url: '/SysException/GetList',
    method: 'post',
    fitColumns: true,
    //toolbar: "#staff_tabTools",
    columns: [[
        {
            field: 'Id',
            title: 'ID',
            width: 40,
            align: 'center',
            checkbox: true,
            hidden: true,
        },
        {
            field: 'HelpLink',
            title: '帮助链接',
            width: 40,
            align: 'center',
        },
        {
            field: 'Message',
            title: '异常信息',
            width: 200,
            align: 'center',
        },
        {
            field: 'Source',
            title: '来源',
            width: 140,
            align: 'center',
        },
        {
            field: 'StackTrace',
            title: '堆栈',
            width: 40,
            align: 'center',
        },
        {
            field: 'TargetSite',
            title: '目标页',
            width: 40,
            align: 'center',
        },
        {
            field: 'Data',
            title: '程序集',
            width: 60,
            align: 'center',
        },
        {
            field: 'CreateTime',
            title: '发生时间',
            width: 65,
            align: 'center',
            formatter: formatDateBoxFull,
        },
    ]],
    pagination: true,
    pageSize: 5,
    pageList: [5, 10, 15],
    sortName: 'Id',
    sortOrder: 'asc',
    rownumbers: true,
});